id2key = {0: "bottom burner", 1: "top burner", 2: "switch", 3: "cabinet", 4: "microwave", 5: "kettle"}
LANGUAGE_DESCRIPTION = {
    'cabinet': [
        "Can you please open the sliding cabinet door for me?",
        "Please open the sliding cabinet door for me.",
        "Can you slide open the cabinet door, please?",
        "Please open the cabinet door on the sliding mechanism right away.",
        "Can you open the cabinet door by sliding it?",
        "Can you open the sliding cabinet door now?",
        "Please slide open the cabinet door for me now.",
        "Could you slide the cabinet door to the side?",
        "Please open the cabinet door by sliding it.",
        "Please slide open the cabinet door.",
        "Can you slide the cabinet door open for me?",
        "I would appreciate it if you could open the sliding cabinet door.",
        "Can you please open the cabinet door for me by sliding it?",
        "Could you please open the sliding cabinet door now?",
        "Can you open the sliding cabinet door as soon as possible?",
        "Could you slide the cabinet door to the side quickly?",
        "Please slide the cabinet door open as quickly as possible.",
        "Could you slide the cabinet door open as soon as possible?",
        "Please open the sliding cabinet door without any delay.",
        "Can you slide open the cabinet door without any delay?",
        "Could you please slide the cabinet door open quickly?",
        "Can you slide the cabinet door open immediately?",
        "Please open the sliding cabinet door promptly.",
        "Can you please slide the cabinet door open immediately?",
        "Would you mind opening the slide cabinet door?",
        "Could you please open the cabinet door on the sliding mechanism?",
        "Please slide open the cabinet door without any delay.",
        "Can you open the sliding cabinet door for me now, please?",
        "Could you slide the cabinet door open as quickly as possible?",
        "Please open the cabinet door by sliding it as soon as possible.",
        "Can you slide open the cabinet door quickly, please?",
        "Could you open the sliding cabinet door immediately?",
        "Please slide the cabinet door open as soon as possible.",
        "Can you please open the cabinet door by sliding it now?",
        "Could you open the sliding cabinet door, please?",
        "Could you please slide open the cabinet door now?",
        "Please slide the cabinet door open immediately.",
        "Could you slide open the cabinet door promptly?",
        "Please slide open the cabinet door right away.",
        "I need your help, open the slide cabinet door please.",

        "Please slide the cabinet door open.",
        "Please slide the cabinet door open now.",
        "Can you open the cabinet door by sliding it without delay?",
        "Could you please open the cabinet door by sliding it?",
        "Can you open the sliding cabinet door right away?",
        "Could you slide the cabinet door open?",
        "Please, would you mind me opening the slide cabinet door",
        "I need you to open the sliding cabinet door.",
        "Can you open the sliding door on the cabinet, please?",
        "Could you please slide the cabinet door open?",
    ],
    'switch': [
            "Please turn on the lights",
            "Can you switch on the lights, please?",
            "Could you illuminate the room for me?",
            "I need some light, can you help me?",
            "Could you turn on the light switch, please?",
            "Switch on the lights, please",
            "Can you activate the lighting system?",
            "Light up the room, please",
            "I want to see better, please turn on the lights",
            "Please, turn on the light switch",
            "Make it brighter in here, can you switch on the lights?",
            "Can you turn on the light source, please?",
            "I need some light, can you switch on the lights?",
            "Please illuminate the room",
            "Turn the lights on, please",
            "Can you switch on the room's lighting, please?",
            "I need some light, can you turn on the lights?",
            "Switch on the room's light, please",
            "Can you brighten up the space?",
            "Can you please activate the light?",
            "Can you light up the room?",
            "Can you switch on the light source, please?",
            "Can you turn on the lighting, please?",
            "Please turn on the light",
            "Please activate the lighting",
            "Can you turn on the lights, please?",
            "I would like some light, can you help me?",
            "Can you please turn on the lights?",
            "Please switch on the lights in this room",
            "I need some light in here, can you turn on the lights?",
            "Can you activate the light switch, please?",
            "Can you please brighten up the room?",
            "I need some illumination, can you help me?",
            "Please switch on the lighting in the room",
            "Please turn on the lighting in this room",
            "Please, switch on the room's lighting",
            "Can you activate the lighting system in this room?",
            "Would you mind me switching the light?",
            "The switch is on.",
            "The switch is turned on by someone.",

            "Please, illuminate the space",
            "Turn on the lights, please",
            "Could you turn on the lighting system?",
            "I need some illumination, can you turn on the lights?",
            "Can you switch on the lights in here, please?",
            "Please, switch on the lights",
            "Please, turn on the lights in this room",
            "Can you brighten up the room?",
            "Please switch on the light",
            "Can you brighten up this space for me?",
    ],
    'microwave': [
            "Please open the door of the microwave.", 
            "Can you open the microwave door for me?", 
            "Hey, can you open the door of the microwave?", 
            "Would you mind opening the microwave door?", 
            "Can you help me by opening the microwave door?", 
            "Can you open the door of the microwave for me, please?", 
            "Please open the microwave door, if you don't mind.", 
            "Can you do me a favor and open the microwave door?", 
            "I would appreciate it if you could open the microwave door.", 
            "Can you please open the microwave door for me?", 
            "It would be great if you could open the door of the microwave.", 
            "Could you kindly open the microwave door?", 
            "I need you to open the door of the microwave.", 
            "Please, open the door of the microwave for me.", 
            "Can you open the microwave door at your earliest convenience?", 
            "Could you open the microwave door when you get a chance?", 
            "Can you open the door of the microwave as soon as possible?", 
            "Would you be able to open the door of the microwave?", 
            "I request that you open the microwave door.", 
            "I would be grateful if you could open the microwave door.", 
            "Please, could you open the door of the microwave?", 
            "I need the door of the microwave to be opened, please.", 
            "Can you open the door of the microwave as quickly as possible?", 
            "Can you quickly open the microwave door?", 
            "Please open the microwave door at your earliest convenience.", 
            "Can you open the microwave door immediately?", 
            "I'd appreciate it if you could open the door of the microwave.", 
            "Can you open the microwave door right now?", 
            "Can you open the door of the microwave quickly, please?", 
            "Could you open the microwave door now?", 
            "Can you open the microwave door without delay?", 
            "Please, open the microwave door as soon as possible.", 
            "I require you to open the door of the microwave.", 
            "Can you please open the microwave door as quickly as possible?", 
            "Can you open the door of the microwave right away?",   
            "Can you quickly open the door of the microwave?", 
            "Please, could you open the microwave door as quickly as possible?",
            "Can you open the microwave door without any delay?", 
            "I would be grateful if you could open the door of the microwave quickly.", 
            "Would it be possible for you to open the door of the microwave?", 
            
            "Can you please open the door of the microwave?", 
            "I need the microwave door to be opened.", 
            "Could you open the door of the microwave quickly?", 
            "Can you open the microwave door quickly?", 
            "I'd like you to open the microwave door for me, please.", 
            "Would you mind opening the door of the microwave for me?", 
            "Can you assist me by opening the microwave door?", 
            "Can you kindly open the door of the microwave?", 
            "Can you please open the microwave door without delay?",
            "Could you please open the door of the microwave?", 
    ],
    'kettle': [
            "Please put the kettle on the burner.",
            "Can you start heating the water in the kettle, please?",
            "Could you fill the kettle with water and place it on the stove?",
            "Hey robot, can you make some tea by boiling water in the kettle?",
            "It's tea time! Could you turn on the stove and place the kettle on top?",
            "I would like some hot water. Can you put the kettle on the burner, please?",
            "Robot, please turn on the burner and put the kettle on top.",
            "I need some hot water. Could you fill the kettle, put it on the stove, and turn on the burner?",
            "Would you mind putting the kettle on the burner and turning on the stove?",
            "Can you please prepare some hot water by placing the kettle on the burner and turning on the heat?",
            "I would like some tea. Could you fill the kettle, place it on the stove, and turn on the burner?",
            "Can you boil some water for me by putting the kettle on the stove?",
            "Robot, can you put the kettle on the burner and turn on the heat?",
            "Can you prepare the kettle for me by putting it on the burner and turning on the heat?",
            "Hey robot, I need hot water. Can you put the kettle on the burner and turn on the stove?",
            "Please turn on the stove and put the kettle on the burner so we can have some hot water.",
            "Hey robot, can you put the kettle on the stove and turn on the heat?",
            "I need hot water for my tea. Can you put the kettle on the burner and turn on the stove?",
            "Please prepare some hot water by placing the kettle on the burner and turning on the stove.",
            "Can you fill the kettle, put it on the stove, and turn on the burner to heat up the water?",
            "Please put the kettle on the burner and turn on the heat so we can have some hot water.",
            "I need hot water to make some tea. Can you put the kettle on the burner and turn on the stove?",
            "Hey robot, can you prepare some hot water by putting the kettle on the burner and turning on the heat?",
            "I would like some hot water. Can you put the kettle on the burner and turn on the stove?",
            "Could you heat up the water in the kettle by putting it on the burner and turning on the heat?",
            "Robot, can you put the kettle on the burner and start heating up the water?",
            "Can you please prepare some hot water by filling the kettle, putting it on the burner, and turning on the heat?",
            "Can you please put the kettle on the stove, robot?",
            "I need a hot cup of tea, robot. Please put the kettle on the burner.",
            "Hey, robot! Can you boil the water in the kettle on the stove for me?",
            "Robot, it's tea time! Please put the kettle on the burner and heat up the water.",
            "I'd love a cup of tea, robot. Can you put the kettle on the stove and get the water boiling?",
            "Robot, can you please start heating up the water in the kettle on the burner?",
            "Robot, can you put the kettle on the stove and boil some water for me, please?",
            "Hey robot, could you heat up the water in the kettle on the burner?",
            "I would love some tea, robot. Can you put the kettle on the stove?",
            "Please start boiling the water in the kettle on the burner, robot.",
            "Hey, robot. Can you please turn on the stove and put the kettle on?",
            "Can you make me some tea, robot? Please put the kettle on the burner.",
            "I'm feeling chilly, robot. Can you put the kettle on the stove and boil some water?",

            "Can you start heating up the water by placing the kettle on the burner and turning on the stove?",
            "Please start boiling some water in the kettle on the burner, robot.",
            "Robot, could you put the kettle on the burner and heat up the water?",
            "Let's make some tea. Can you put the kettle on the burner and turn on the heat?",
            "Can you please heat up some water by putting the kettle on the burner and turning on the stove?",
            "Please heat up the kettle by putting it on the burner.",
            "Please put the kettle on the burner, robot. I'm craving a cup of tea.",
            "I need some hot water. Can you put the kettle on the stove and turn on the burner?",
            "Can you please boil some water by putting the kettle on the burner and turning on the stove?",
            "I'm craving some tea. Can you put the kettle on the burner and turn on the heat?",
    ],
    'top burner':[
        "Can you turn the knob that activates the top burner on the oven?",
        "Could you kindly activate the top burner by turning the oven knob?",
        "Activate the top burner by turning the oven knob please",
        "Turn the oven knob to switch on the top burner",
        "Twist the oven knob to activate the top burner",
        "The top burner can be activated by turning the oven knob",
        "Please switch on the top burner by turning the oven knob",
        "Activate the top burner by turning the oven knob clockwise",
        "Kindly turn the oven knob to activate the top burner",
        "Use the oven knob to activate the top burner",
        "To turn on the top burner, turn the oven knob",
        "The oven knob controls the top burner, please turn it",
        "Would you turn the oven knob to activate the top burner?",
        "Twist the oven knob to turn on the top burner",
        "Please turn the oven knob to switch on the top burner",
        "The top burner can be activated by turning the oven knob clockwise",
        "Can you activate the top burner by turning the oven knob right?",
        "Turn the oven knob to the right to activate the top burner",
        "The top burner is activated.", 
        "Activate the top burner by turning the oven knob in a clockwise direction",       
        "Use the oven knob to turn on the top burner, please",
        "To switch on the top burner, turn the oven knob right",
        "Please turn the oven knob to the right to switch on the top burner",
        "Can you turn the oven knob to activate the top burner on the stove?",
        "Could you activate the top burner by turning the oven knob clockwise?",
        "Please activate the top burner by turning the oven knob to the right",
        "Twist the oven knob to switch on the top burner, please",
        "Turn the oven knob clockwise to switch on the top burner",
        "Can you please turn the oven knob to activate the top burner?",
        "Kindly turn the oven knob to switch on the top burner",
        "The top burner can be activated by turning the oven knob to the right",
        "Activate the top burner by turning the oven knob clockwise, please",
        "Please turn the oven knob to activate the top burner on the stove",
        "Twist the oven knob to activate the top burner on the stove, please",
        "Could you turn the oven knob to activate the top burner on the stove?",
        "Activate the top burner by turning the oven knob to the right on the stove",
        "Please turn the oven knob to switch on the top burner on the stove",
        "The top burner can be activated by turning the oven knob to the right on the stove",
        "Use the oven knob to turn on the top burner on the stove, please",
        "Turn the knob on the oven that corresponds to the top burner.",

        "Twist the oven knob to turn on the top burner.",
        "Manipulate the oven knob to activate the top burner.",
        "Turn the oven knob to the right to activate the top burner on the stove",
        "Could you please turn the oven knob to activate the top burner?",
        "Use the oven knob to activate the top burner on the stove",
        "Please turn the oven knob to activate the top burner",
        "Turn the oven knob clockwise to activate the top burner on the stove",
        "Use the oven knob to switch on the top burner on the stove",
        "Can you turn on the top burner by twisting the oven knob?",
        "Turning the oven knob will switch on the top burner",
    ],
    'bottom burner':[
        "Can you turn the knob on the oven that activates the bottom right burner?",
        "Please turn the knob on the oven that activates the bottom right burner.",
        "Activate the bottom right burner on the oven by turning the knob.",
        "Would you mind turning the knob on the oven that activates the bottom right burner?",
        "Turn the knob on the oven to activate the bottom right burner, please.",
        "Could you turn the knob on the oven so that the bottom right burner activates?",
        "Robot, please turn the knob on the oven to activate the bottom right burner.",
        "Activate the bottom right burner by turning the oven knob.",
        "Robot, turn the knob on the oven that activates the bottom right burner.",
        "Please turn the knob on the oven to activate the bottom right burner, Robot.",
        "Can you activate the bottom right burner by turning the knob on the oven?",
        "Would you kindly turn the knob on the oven so that the bottom right burner activates?",
        "Could you activate the bottom right burner on the oven by turning the knob?",
        "Robot, please turn the oven knob to activate the bottom right burner.",
        "Activate the bottom right burner by turning the knob on the oven, Robot.",
        "Robot, turn the knob on the oven to activate the bottom right burner, please.",
        "Please turn the oven knob to activate the bottom right burner, Robot.",
        "Would you mind activating the bottom right burner on the oven by turning the knob?",
        "Could you please turn the knob on the oven to activate the bottom right burner, Robot?",
        "Robot, would you kindly turn the knob on the oven so that the bottom right burner activates?",
        "Please activate the bottom right burner by turning the oven knob, Robot.",
        "Can you turn the oven knob to activate the bottom right burner, Robot?",
        "Robot, please turn the oven knob so that the bottom right burner activates.",
        "Could you turn the oven knob to activate the bottom right burner, please?",
        "Please turn the oven knob to activate the bottom right burner.",
        "Robot, please activate the bottom right burner on the oven by turning the knob.",
        "Would you kindly turn the oven knob to activate the bottom right burner?",
        "Can you turn the oven knob to activate the bottom right burner, please?",
        "Could you turn the oven knob so that the bottom right burner activates, Robot?",
        "Turn the oven knob to activate the bottom right burner, please, Robot.",
        "Would you mind turning the oven knob so that the bottom right burner activates, Robot?",
        "Can you turn the oven knob so that the bottom right burner activates, Robot?",
        "Activate the bottom right burner by turning the knob on the oven, please, Robot.",
        "Robot, please activate the bottom right burner by turning the knob on the oven.",
        "Rotate the oven knob for the burner located on the bottom right.",
        "Turn the knob on the oven to activate the burner in the bottom right corner.",
        "Manipulate the oven knob to turn on the burner at the bottom right.",
        "Activate the bottom right burner by turning the knob located on the oven.",
        "Turn the oven knob to activate the bottom burner.",
        "Please turn the oven knob so that the bottom burner activates, Robot.",
        
        "Would you mind turning the oven knob to activate the bottom burner?",
        "The bottom burner is activated.",
        "Rotate the knob located on the oven to start the burner at the bottom right.",
        "Please turn the oven knob so that the bottom right burner activates, Robot.",
        "Please activate the bottom right burner on the oven by turning the knob, Robot.",
        "Would you mind turning the oven knob to activate the bottom right burner, Robot?",
        "Activate the bottom right burner on the oven by turning the knob, please.",
        "Turn the knob on the oven in order to activate the bottom right burner.",
        "Adjust the oven knob to the position that turns on the burner at the bottom right.",
        "Turn the oven knob to activate the bottom right burner, Robot.",
    ]
}
